In [14]:
import numpy as np
import pandas as pd

In [15]:
# DataFrame 1
employees = pd.DataFrame({
    'employee_id':[1,2,3,4,5],
    'name':['John','Anna','Peter','Linda','Bob'],
    'department':['HR','IT','Finance','IT','HR']
})

In [16]:
# DataFrame 2 
salaries = pd.DataFrame({
    'employee_id':[1,2,3,4,5],
    'salary':[60000,80000,65000,70000,90000],
    'bonus':[5000,10000,7000,8000,12000]
})

# Merging 2 Dataframe

In [20]:
# Using a .merge() // merges a DataFrame

pd.merge(employees,salaries) # it will merge the both dataframe

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            4  Linda         IT   70000   8000
4            5    Bob         HR   90000  12000

**on=**  If common columns is both dataframe you can use as a join

**how='inner'**  It give the inner value means the based on 1 employees

**how='outer'**  Gives all inner + outer value , mean both dataframe

**how='left'** We want merge basis on left(employee) i want all the id on that present on employees

**how='right'** if i do operation right basis it will perform on salaries

If there are empty values in dataframe it will showns as Nan

In [21]:
pd.merge(employees,salaries,on='employee_id',how='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            4  Linda         IT   70000   8000
4            5    Bob         HR   90000  12000

In [23]:
pd.merge(employees,salaries,on='employee_id',how='outer')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            4  Linda         IT   70000   8000
4            5    Bob         HR   90000  12000

In [24]:
pd.merge(employees,salaries,on='employee_id',how='left')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            4  Linda         IT   70000   8000
4            5    Bob         HR   90000  12000

In [25]:
pd.merge(employees,salaries,on='employee_id',how='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            4  Linda         IT   70000   8000
4            5    Bob         HR   90000  12000

# Concatination of 2 dataframe

In [40]:
df1 = pd.DataFrame({
    'A':['A0','A1','A2'],
    'B':['B0','B1','B2'],
    'C':['C0','C1','C2']
})

In [41]:
df2 = pd.DataFrame({
    'A':['A3','A4','A5'],
    'B':['B3','B4','B5'],
    'C':['C3','C4','C5']
})

In [34]:
# For Concatination we use function .concat()

# pd.concat(df1,df2) it will not work

pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

# Joining of 2 Dataframe

In [48]:
df1 = pd.DataFrame({
    'name':['Alice','Bob','Charlie']    
},index=[1,2,3])

In [49]:
df2 = pd.DataFrame({
    'score':[85,90,75]    
},index=[2,3,4])

In [50]:
# For join 1 dataframe to other dataframe we use .join()

df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0