# Missing data

In missing data you fill the data of remove the element , you want to remove the element , you want to create a algorithm you dont want to messy data in it

In [1]:
import numpy as np
import pandas as pd

In [20]:
# np.nan = null value

data = {
    'A':[1,2,3,4,5],
    'B':[np.nan,2,3,4,5],
    'C':[1,2,3,np.nan,np.nan],
    'D':[1,np.nan,np.nan,np.nan,5]
}

df = pd.DataFrame(data)
df

   A    B    C    D
0  1  NaN  1.0  1.0
1  2  2.0  2.0  NaN
2  3  3.0  3.0  NaN
3  4  4.0  NaN  NaN
4  5  5.0  NaN  5.0

**Finding Missing Data**

In [21]:
# .isna() check the null value in data if present output is True

df.isna() # show data which one is nan represents as True

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2  False  False  False   True
3  False  False   True   True
4  False  False   True  False

In [22]:
# for the count of nan value in Dataframe

df.isna().sum()

A    0
B    1
C    2
D    3
dtype: int64

In [23]:
# To check in column ( or Row ) is null value , use .any()

df.isna().any()

A    False
B     True
C     True
D     True
dtype: bool

**Removing Missing Data**

In [24]:
df.dropna() # use for removing the null value , works on row , but this removes whole row of null value if 1 nan is present

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [27]:
# there comes a thresh you can set limit how much nan is allowed in df , You have Atleast NonValue of 3 (thresh=3)

df.dropna(thresh=3)

   A    B    C    D
0  1  NaN  1.0  1.0
1  2  2.0  2.0  NaN
2  3  3.0  3.0  NaN
4  5  5.0  NaN  5.0

**Filling the missing value**

In [31]:
# df.fillna() to fill the data is null value , it only apply on column

df.fillna(1) # it will be replace the Nan value to 1 , change will not happen in original dp ,
             #because we not using a ( inplace="True" ) only it can change a df Permentetly

   A    B    C    D
0  1  1.0  1.0  1.0
1  2  2.0  2.0  1.0
2  3  3.0  3.0  1.0
3  4  4.0  1.0  1.0
4  5  5.0  1.0  5.0

In [36]:
# you can do like this also if you want a specific column a specific values comes as you input , For a different values for each column
values = {'A':100,'B':200,'C':300,'D':400} # if there is no nan value in columnn , no values output will be there

In [37]:
df.fillna(value=values)

   A      B      C      D
0  1  200.0    1.0    1.0
1  2    2.0    2.0  400.0
2  3    3.0    3.0  400.0
3  4    4.0  300.0  400.0
4  5    5.0  300.0    5.0

In [44]:
# you want to fill mean value on nan value

df.fillna(df.mean()) # it fill thw value of nan with mean value

   A    B    C    D
0  1  3.5  1.0  1.0
1  2  2.0  2.0  3.0
2  3  3.0  3.0  3.0
3  4  4.0  2.0  3.0
4  5  5.0  2.0  5.0