In [1]:
import numpy as np
import pandas as pd

# DataFrame Basic Operations

In [3]:
df = pd.DataFrame({
    'A':[1,2,3,4,5],
    'B':[10,20,30,40,50],
    'C':[100,200,300,400,500]
})

df

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [4]:
df.shape

(5, 3)

In [7]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [10]:
df.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [11]:
# Broadcasting

df['A'] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

In [14]:
df

   A   B    C
0  1  20  100
1  2  30  200
2  3  40  300
3  4  50  400
4  5  60  500

# DataFrame Applying Functions

In [20]:
def square(x):
    return x**2

In [21]:
df['B'].apply(square)

0     400
1     900
2    1600
3    2500
4    3600
Name: B, dtype: int64

In [27]:
# If you wanna change in B Permentely we use - df['']=df[''].apply(square)

df['B'] = df['B'].apply(square)

In [29]:
df

   A                B    C
0  1      25600000000  100
1  2     656100000000  200
2  3    6553600000000  300
3  4   39062500000000  400
4  5  167961600000000  500

In [30]:
# you can create a new columns using as df['B'] / df['D']

df['D'] = df['B'].apply(square)

In [31]:
df

   A                B    C                              D
0  1      25600000000  100          655360000000000000000
1  2     656100000000  200       430467210000000000000000
2  3    6553600000000  300     42949672960000000000000000
3  4   39062500000000  400   1525878906250000000000000000
4  5  167961600000000  500  28211099074560000000000000000