In [10]:
import numpy as np
import pandas as pd

In [11]:
data = {
    'date':pd.date_range('2023-01-01',periods=20),
    'product':['A','B','C','D']*5,
    'region':['East','West','North','South','East','West','North','South','East','West','North','South','East','West','North','South','East','West','North','South'],
    'sales':np.random.randint(10,1000,20),
    'unit':np.random.randint(10,100,20),
    'Rep':['John','Mary','Bob','Alice','John','Mary','Bob','Alice','John','Mary','Bob','Alice','John','Mary','Bob','Alice','John','Mary','Bob','Alice']
}

df = pd.DataFrame(data)

In [12]:
df

         date product region  sales  unit    Rep
0  2023-01-01       A   East    846    95   John
1  2023-01-02       B   West     85    45   Mary
2  2023-01-03       C  North    950    14    Bob
3  2023-01-04       D  South    333    18  Alice
4  2023-01-05       A   East    299    75   John
5  2023-01-06       B   West    312    83   Mary
6  2023-01-07       C  North    127    89    Bob
7  2023-01-08       D  South    164    47  Alice
8  2023-01-09       A   East    414    11   John
9  2023-01-10       B   West    378    49   Mary
10 2023-01-11       C  North    824    76    Bob
11 2023-01-12       D  South    997    11  Alice
12 2023-01-13       A   East     16    84   John
13 2023-01-14       B   West    796    72   Mary
14 2023-01-15       C  North    882    39    Bob
15 2023-01-16       D  South    203    48  Alice
16 2023-01-17       A   East    373    79   John
17 2023-01-18       B   West    260    62   Mary
18 2023-01-19       C  North    869    71    Bob
19 2023-01-20       D  South    502    87  Alice

In [13]:
df['month']=df['date'].dt.month_name()
df

         date product region  sales  unit    Rep    month
0  2023-01-01       A   East    846    95   John  January
1  2023-01-02       B   West     85    45   Mary  January
2  2023-01-03       C  North    950    14    Bob  January
3  2023-01-04       D  South    333    18  Alice  January
4  2023-01-05       A   East    299    75   John  January
5  2023-01-06       B   West    312    83   Mary  January
6  2023-01-07       C  North    127    89    Bob  January
7  2023-01-08       D  South    164    47  Alice  January
8  2023-01-09       A   East    414    11   John  January
9  2023-01-10       B   West    378    49   Mary  January
10 2023-01-11       C  North    824    76    Bob  January
11 2023-01-12       D  South    997    11  Alice  January
12 2023-01-13       A   East     16    84   John  January
13 2023-01-14       B   West    796    72   Mary  January
14 2023-01-15       C  North    882    39    Bob  January
15 2023-01-16       D  South    203    48  Alice  January
16 2023-01-17       A   East    373    79   John  January
17 2023-01-18       B   West    260    62   Mary  January
18 2023-01-19       C  North    869    71    Bob  January
19 2023-01-20       D  South    502    87  Alice  January

In [15]:
df['Quater']='Q'+df['date'].dt.quater_astype(str)
df

AttributeError: 'DatetimeProperties' object has no attribute 'quater_astype'

In [17]:
pd.pivot_table(df,values='sales',index='region',columns='product')

product      A      B      C      D
region
East     389.6    NaN    NaN    NaN
North      NaN    NaN  730.4    NaN
South      NaN    NaN    NaN  439.8
West       NaN  366.2    NaN    NaN

In [18]:
pd.pivot_table(df,values=['sales','unit'],index='region',columns='product')

         sales                       unit
product      A      B      C      D     A     B     C     D
region
East     389.6    NaN    NaN    NaN  68.8   NaN   NaN   NaN
North      NaN    NaN  730.4    NaN   NaN   NaN  57.8   NaN
South      NaN    NaN    NaN  439.8   NaN   NaN   NaN  42.2
West       NaN  366.2    NaN    NaN   NaN  62.2   NaN   NaN

**Cross Tab**

In [20]:
pd.crosstab(df['region'],df['product']) # it show count per rows

product  A  B  C  D
region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0