# Series 
A Series is one-dimensional labeled array capable of holding any datatype this axis labels are collectively called the index

**Creating Series**

There are multiple ways to create a pandas series:
--> [1,2,3,4]    

series = Column

In [7]:
import numpy as np
import pandas as pd

In [19]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array(my_list) 
dictn = {
    "A":10,
    "B":20,
    "C":30
}

In [20]:
# To create a series we use a .series()
pd.Series(my_list) # create a series , S should be capital letter
# in Series a output will be in vertically (labelsb)

0    10
1    20
2    30
dtype: int64

In [21]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [26]:
pd.Series(dictn) # we use as series we automatically set index by use key : value pair

A    10
B    20
C    30
dtype: int64

In [25]:
pd.Series(my_list,index=labels) # custom series index , you can customize a index as your list as given here is labels

a    10
b    20
c    30
dtype: int64

# Dataframe ( dictionaries , list )

when we combine a multiple series together it will become a Dataframe

In [23]:
import numpy as np
import pandas as pd

**Creating a Dataframe**

In [27]:
data = {
    'name':['john','anna','peter','linda'],
    'age':[28,34,29,42],
    'city':['new york','paris','berlin','london'],
    'salary':[65000,70000,62000,85000]    
}

In [29]:
pd.DataFrame(data) # create a dataframe of data dict

    name  age      city  salary
0   john   28  new york   65000
1   anna   34     paris   70000
2  peter   29    berlin   62000
3  linda   42    london   85000

In [58]:
df = pd.DataFrame(data) # it will show df with title or column name , we store dataframe as df
df

    name  age      city  salary
0   john   28  new york   65000
1   anna   34     paris   70000
2  peter   29    berlin   62000
3  linda   42    london   85000

In [48]:
columns = ['name','age'] # we use it when we want some of columns in output

In [49]:
df = pd.DataFrame(data,columns=columns)
df

    name  age
0   john   28
1   anna   34
2  peter   29
3  linda   42

**Selection and Indexing of columns**

In [51]:
df['name'] # Selecting a columns from name

0     john
1     anna
2    peter
3    linda
Name: name, dtype: object

In [54]:
# for both or multiple column access use [[ex1,ex2]] list of list type

df[['name','age']]

    name  age
0   john   28
1   anna   34
2  peter   29
3  linda   42

**Creating a new column**

In [69]:
# for creating a new column we create as basic like df["new_column_name"]=['val1','val2',...'valn']

df['designation']=['IT','HR','Doctor','CEO'] # added new column at df you can add with 4 value existing not less more
df

    name  age      city  salary designation
0   john   28  new york   65000          IT
1   anna   34     paris   70000          HR
2  peter   29    berlin   62000      Doctor
3  linda   42    london   85000         CEO

**Removing a column**

In [64]:
# for dropping a column we use a .drop 
# df.drop('designation') it will show error like axis , cannot found is axis

df.drop('designation',axis=1) # because axis=0 works on rows you get error , remove only on copy or temporary but in df is present

    name  age      city  salary
0   john   28  new york   65000
1   anna   34     paris   70000
2  peter   29    berlin   62000
3  linda   42    london   85000

In [70]:
# that why here comes a inplace that drop a column a permantetly , inplace=True

df.drop('designation',axis=1,inplace=True) # Delete a permentetly Column

In [72]:
# for drop a row also work

df.drop(0,axis=0) # it remove a row .drop(index_no,axis=1/0) 1 = column , 0 = row

    name  age    city  salary
1   anna   34   paris   70000
2  peter   29  berlin   62000
3  linda   42  london   85000

**Selecting Rows**

In [75]:
# for accessing or selecting the row .loc(label based)

df.loc[0] # it show a row = 0 value .loc(location)

name          john
age             28
city      new york
salary       65000
Name: 0, dtype: object

In [82]:
# for accessing a row and column 

df.loc[0:2,'name'] # as .loc[row,column]

0     john
1     anna
2    peter
Name: name, dtype: object

In [77]:
# for accessing a multiple rows [[val1,val2]] like list of list

df.loc[[1,3]]

    name  age    city  salary
1   anna   34   paris   70000
3  linda   42  london   85000

In [79]:
# we can slice a value also we want particular value

df.loc[0:2] # Note: This returns rows 0, 1, and 2 (excludes index 3)

    name  age      city  salary
0   john   28  new york   65000
1   anna   34     paris   70000
2  peter   29    berlin   62000

In [ ]:
# Boolean Indexing: df.loc[df['age'] > 30] — This is the most common way to filter data based on conditions.
# List of Labels: df.loc[['r1', 'r2'], ['c1', 'c2']]

In [85]:
# i stand for index location .iloc(integer-location-based)
df.iloc[0] 

# Negative Indexing: df.iloc[-1] returns the very last row

name          john
age             28
city      new york
salary       65000
Name: 0, dtype: object

**Selecting Subsets of rows and columns**

In [84]:
# The general syntax is: df.loc[row_selection, column_selection]. 

df.loc[[0,1],['name','age']]

   name  age
0  john   28
1  anna   34

In [86]:
# Pratice work :
df.loc[[2,3],['name','age']]

    name  age
2  peter   29
3  linda   42

**Conditional Selection**

In [90]:
# ( < , > , <= , >= , ! , != , == )

# Q1. I only want to see those people whose age is above 30 . syntax : df[df["Col"]>0]

df[df['age']>30]

    name  age    city  salary
1   anna   34   paris   70000
3  linda   42  london   85000

In [102]:
# I only want to see those people whose age is above 30 there city must be paris
df[(df['age']>30) & (df['city']=="paris")]

   name  age   city  salary
1  anna   34  paris   70000